const scholarships = [
  {
    "name": "Erasmus Mundus EMINENT",
    "university": "Erasmus Mundus Consortium",
    "country": "Europe (Greece/Multi-country)",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "Computer Science / IoT / Embedded Systems",
    "deadline": "March (annual)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bachelor's in relevant field; strong academic record; motivation letter",
    "notes": "",
    "link": "https://www.applykite.com/scholarships/fully-funded-erasmus-mundus-masters-in-embedded-intelligence-nanotechnology-and-iot-europe-20262028-zov6ru0h2m",
    "benefits": "Tuition 100% + €1400/month stipend + health insurance + travel",
    "competition": "High"
  },
  {
    "name": "KAIST Graduate Scholarship",
    "university": "KAIST",
    "country": "South Korea",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Engineering / IoT / Science",
    "deadline": "Varies by semester",
    "funding": "Fully Funded",
    "assistantship": "RA",
    "eligibility": "Bachelor's in relevant field; all intl students eligible on admission",
    "notes": "",
    "link": "https://kaistscholarship.com/graduate-scholarship/",
    "benefits": "Full tuition + 350000 KRW/month",
    "competition": "Medium"
  },
  {
    "name": "MEXT Scholarship (Japanese Govt)",
    "university": "Various Japanese Universities",
    "country": "Japan",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "Engineering / Science / Technology",
    "deadline": "Apr-Jun (Embassy) / Nov (Univ)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bachelor's degree; under 35; good academic record",
    "notes": "",
    "link": "https://www.studyinjapan.go.jp/en/smap-stopj-applications-702.html",
    "benefits": "Full tuition + 143000 JPY/month + airfare",
    "competition": "High"
  },
  {
    "name": "Commonwealth Master's Scholarships",
    "university": "Commonwealth Scholarship Commission",
    "country": "United Kingdom",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "All Subjects (incl. Engineering)",
    "deadline": "Dec-Jan (annual)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Commonwealth country citizen (Bangladesh eligible); cannot self-fund",
    "notes": "",
    "link": "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships",
    "benefits": "Full tuition + living allowance + airfare + thesis grant",
    "competition": "High"
  },
  {
    "name": "DAAD EPOS Scholarship",
    "university": "DAAD / German Universities",
    "country": "Germany",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Engineering / Development-Related",
    "deadline": "Oct-Nov (annual)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bachelor's + 2 yrs work exp preferred; developing country",
    "notes": "",
    "link": "https://www.daad.de/en/information-services-for-higher-education-institutions/further-information-on-daad-programmes/epos/",
    "benefits": "No tuition + €934/month + insurance + travel",
    "competition": "Medium"
  },
  {
    "name": "Chevening Scholarship",
    "university": "UK Government (FCDO)",
    "country": "United Kingdom",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "All Subjects (incl. Engineering)",
    "deadline": "Aug-Nov (annual)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bachelor's; 2+ yrs work experience; leadership potential",
    "notes": "",
    "link": "https://www.chevening.org/scholarships/",
    "benefits": "Full tuition + monthly stipend + travel + thesis grant",
    "competition": "High"
  },
  {
    "name": "Commonwealth Shared Scholarships",
    "university": "CSC + UK Universities",
    "country": "United Kingdom",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Development-related subjects",
    "deadline": "Dec-Jan (annual)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Commonwealth developing country; not previously studied in dev country",
    "notes": "",
    "link": "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-shared-scholarships",
    "benefits": "Full tuition + living allowance + airfare",
    "competition": "Medium"
  },
  {
    "name": "ADB-Japan Scholarship Program",
    "university": "Asian Development Bank",
    "country": "Asia-Pacific / USA",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Engineering / Technology / Economics",
    "deadline": "Varies by university",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "ADB borrowing member (Bangladesh qualifies); bachelor's degree",
    "notes": "",
    "link": "https://www.adb.org/what-we-do/education/programs/japan-scholarship-program",
    "benefits": "Full tuition + monthly stipend + travel + books",
    "competition": "Medium"
  },
  {
    "name": "Tokyo Tech MEXT Scholarship",
    "university": "Tokyo Institute of Technology",
    "country": "Japan",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "Engineering / Science / Technology",
    "deadline": "Nov-Dec (University Rec)",
    "funding": "Fully Funded",
    "assistantship": "RA",
    "eligibility": "Bachelor's degree; research proposal; supervisor match",
    "notes": "",
    "link": "https://www.titech.ac.jp/english/0/admissions/prospective-students",
    "benefits": "Full tuition + 143000 JPY/month + airfare",
    "competition": "High"
  },
  {
    "name": "Hokkaido e3 Program (MEXT)",
    "university": "Hokkaido University",
    "country": "Japan",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Engineering (English-taught)",
    "deadline": "Nov (University Rec)",
    "funding": "Fully Funded",
    "assistantship": "RA",
    "eligibility": "Bachelor's in engineering; English proficiency",
    "notes": "",
    "link": "https://eprogram.eng.hokudai.ac.jp/e3/scholarships/mext",
    "benefits": "Full tuition + 143000 JPY/month + airfare",
    "competition": "Medium"
  },
  {
    "name": "Erasmus Mundus Manufacturing 4.0 (meta4.0)",
    "university": "Erasmus Mundus Consortium",
    "country": "Europe (Multi-country)",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "Manufacturing / Industry 4.0 / Digital Mfg",
    "deadline": "Feb-March (annual)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bachelor's in engineering; motivation for smart manufacturing",
    "notes": "",
    "link": "https://daadscholarship.com/manufacturing-4-0-scholarship-2026-erasmus-mundus-joint-program/",
    "benefits": "Full tuition + monthly stipend + travel + insurance",
    "competition": "High"
  },
  {
    "name": "POSCO Asia Fellowship",
    "university": "POSCO TJ Park Foundation",
    "country": "South Korea",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Engineering / Science / Technology",
    "deadline": "Varies",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Asian country; bachelor's; strong record; under 35",
    "notes": "",
    "link": "https://opportunitiescorners.com/posco-asia-fellowship-2026/",
    "benefits": "Full tuition + living expenses + airfare",
    "competition": "Medium"
  },
  {
    "name": "TU/e Graduate Scholarship",
    "university": "Eindhoven University of Technology",
    "country": "Netherlands",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "Engineering / AI / Data Science",
    "deadline": "Apr-May",
    "funding": "Partial to Full",
    "assistantship": "None",
    "eligibility": "Bachelor's in relevant field; excellent record; non-EU/EEA",
    "notes": "",
    "link": "https://www.tue.nl/en/education/become-a-tue-student/masters-programs/scholarships",
    "benefits": "Tuition waiver + stipend (varies)",
    "competition": "High"
  },
  {
    "name": "University of Twente Scholarship",
    "university": "University of Twente",
    "country": "Netherlands",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Engineering / Technology / Science",
    "deadline": "May 1 2026",
    "funding": "Partial",
    "assistantship": "None",
    "eligibility": "Non-EU/EEA student; strong academic record",
    "notes": "",
    "link": "https://www.utwente.nl/en/education/scholarship-finder/university-of-twente-scholarship/",
    "benefits": "€3000–€22000 towards tuition",
    "competition": "Medium"
  },
  {
    "name": "RWTH Aachen Global Talent Scholarship",
    "university": "RWTH International Academy",
    "country": "Germany",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Engineering / Management & Engineering",
    "deadline": "Varies",
    "funding": "Partial",
    "assistantship": "None",
    "eligibility": "Bachelor's in engineering; strong record; diversity factor",
    "notes": "",
    "link": "https://www.academy.rwth-aachen.de/en/services/scholarships",
    "benefits": "Tuition reduction or stipend support",
    "competition": "Medium"
  },
  {
    "name": "UMass Lowell Global Engineering Leaders",
    "university": "University of Massachusetts Lowell",
    "country": "USA",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Engineering (various)",
    "deadline": "Priority deadlines",
    "funding": "Partial",
    "assistantship": "RA",
    "eligibility": "International student; Master's in engineering; academic excellence",
    "notes": "",
    "link": "https://uml.edu/grad/costs/global-engineering-leaders.aspx",
    "benefits": "$20000 ($5000/semester × 4)",
    "competition": "Medium"
  },
  {
    "name": "GREAT Scholarships (UK)",
    "university": "British Council + UK Universities",
    "country": "United Kingdom",
    "degree": "Master's",
    "priority": "Low",
    "match": 85,
    "field": "Varies by university",
    "deadline": "Varies",
    "funding": "Partial",
    "assistantship": "None",
    "eligibility": "National of Bangladesh; overseas student; accepted to Master's",
    "notes": "",
    "link": "https://study-uk.britishcouncil.org/scholarships/great-scholarships",
    "benefits": "£10000 tuition fee reduction",
    "competition": "Low"
  },
  {
    "name": "Cranfield GREAT Scholarship Bangladesh",
    "university": "Cranfield University + British Council",
    "country": "United Kingdom",
    "degree": "Master's",
    "priority": "Low",
    "match": 85,
    "field": "Engineering / Technology / Management",
    "deadline": "May 18 2026",
    "funding": "Partial",
    "assistantship": "None",
    "eligibility": "Bangladeshi passport holder and resident",
    "notes": "",
    "link": "https://www.cranfield.ac.uk/funding/funding-opportunities/great-cranfield-university-scholarship-bangladesh",
    "benefits": "£10000 towards tuition",
    "competition": "Low"
  },
  {
    "name": "Sussex Bangladesh Scholarship",
    "university": "University of Sussex",
    "country": "United Kingdom",
    "degree": "Master's",
    "priority": "Low",
    "match": 85,
    "field": "All Subjects",
    "deadline": "Varies",
    "funding": "Partial",
    "assistantship": "None",
    "eligibility": "National of Bangladesh; overseas; self-financing",
    "notes": "",
    "link": "https://www.sussex.ac.uk/study/fees-funding/masters-scholarships/view/1765-Sussex-Bangladesh-Scholarship-Masters",
    "benefits": "£4000 tuition fee reduction",
    "competition": "Low"
  },
  {
    "name": "IUJ Scholarships",
    "university": "International University of Japan",
    "country": "Japan",
    "degree": "Master's",
    "priority": "Low",
    "match": 85,
    "field": "Multiple Fields (incl. Technology)",
    "deadline": "Varies",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "International student; bachelor's; English proficiency",
    "notes": "",
    "link": "https://www.iuj.ac.jp/admis/scholarship-financial-aid/",
    "benefits": "Full tuition + living stipend",
    "competition": "Low"
  },
  {
    "name": "Erasmus Mundus EMAI",
    "university": "Erasmus Mundus Consortium",
    "country": "Europe (Spain/Italy/Netherlands/Slovenia)",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "Artificial Intelligence / ML / Robotics / Cybersecurity",
    "deadline": "January (annual)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bachelor's ≥180 ECTS in ICT/Engineering/Physics/Math; IELTS 6.5 or TOEFL 90",
    "notes": "",
    "link": "https://www.upf.edu/web/masters/2_preinscripcio",
    "benefits": "Tuition 100% + €1400/month + travel €2000-3000/yr + insurance + €1000 installation",
    "competition": "High"
  },
  {
    "name": "Erasmus Mundus CyberMACS",
    "university": "Erasmus Mundus Consortium",
    "country": "Europe (Turkey/Germany/North Macedonia)",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "Applied Cybersecurity / Network Security / Cryptography",
    "deadline": "December (annual)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bachelor's in CS/Math or related; good grades; English proficiency",
    "notes": "",
    "link": "https://cybermacs.eu/apply/",
    "benefits": "Tuition 100% + €1400/month + travel €2000-3000/yr + insurance + €1000 installation",
    "competition": "High"
  },
  {
    "name": "Erasmus Mundus CYBERUS",
    "university": "Erasmus Mundus Consortium",
    "country": "Europe (France/Luxembourg/Estonia/Belgium)",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "Cybersecurity",
    "deadline": "February (annual)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bachelor's in CS/Engineering; English proficiency",
    "notes": "",
    "link": "https://cyberus-emjm.eu/",
    "benefits": "Tuition 100% + €1400/month + travel + insurance",
    "competition": "High"
  },
  {
    "name": "Erasmus Mundus CoDaS",
    "university": "Erasmus Mundus Consortium",
    "country": "Europe (Finland/Portugal/Germany/Spain/France)",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "Communications Engineering / Data Science / IoT / 5G-6G",
    "deadline": "January (annual)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bachelor's in Engineering/CS/EE/Data Science; good GPA; English proficiency",
    "notes": "",
    "link": "https://www.unite-codas-master.eu/admission.html#apply",
    "benefits": "Tuition 100% + €1400/month + travel + insurance",
    "competition": "High"
  },
  {
    "name": "Erasmus Mundus EMSSE",
    "university": "Erasmus Mundus Consortium",
    "country": "Europe (France/Italy/Spain/Albania)",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Sustainable Systems Engineering / Smart Manufacturing",
    "deadline": "March (annual)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bachelor's in engineering; English proficiency",
    "notes": "",
    "link": "https://emsse-master.eu/",
    "benefits": "Tuition 100% + €1400/month + travel + insurance",
    "competition": "Medium"
  },
  {
    "name": "UNIST Graduate Scholarship",
    "university": "Ulsan National Institute of Science and Technology",
    "country": "South Korea",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Engineering / AI / Computer Science / Materials / Energy",
    "deadline": "Jul 2026 (1st intake) / Oct 2026 (2nd intake)",
    "funding": "Fully Funded",
    "assistantship": "RA",
    "eligibility": "Bachelor's degree; TOEFL/IELTS; study plan + personal statement",
    "notes": "",
    "link": "https://admg-intl.unist.ac.kr/",
    "benefits": "Full tuition (KRW 3.84M/sem) + KRW 800K-1.44M/month + dormitory",
    "competition": "Medium"
  },
  {
    "name": "GIST International Scholarship",
    "university": "Gwangju Institute of Science and Technology",
    "country": "South Korea",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Engineering / AI / Science / Technology",
    "deadline": "Varies by semester",
    "funding": "Fully Funded",
    "assistantship": "RA",
    "eligibility": "Bachelor's degree; English proficiency; research interest",
    "notes": "",
    "link": "https://www.gist.ac.kr/en/html/sub05/050201.html",
    "benefits": "Full tuition + KRW 140K/month + KRW 120K intl allowance + research stipend",
    "competition": "Medium"
  },
  {
    "name": "Global Korea Scholarship (GKS)",
    "university": "Korean Government (NIIED)",
    "country": "South Korea",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "All Subjects (incl. Engineering)",
    "deadline": "Feb-Mar (Embassy) / Mar-Apr (University)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Under 40; bachelor's; GPA 80%+; developing country citizen (Bangladesh eligible)",
    "notes": "",
    "link": "https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do",
    "benefits": "Full tuition + KRW 1M/month + airfare + settlement + insurance + Korean language training",
    "competition": "High"
  },
  {
    "name": "KOICA Bangladesh Scholarship",
    "university": "KOICA/Korean Government",
    "country": "South Korea",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Development Studies / Public Administration / Engineering",
    "deadline": "March-April 2026",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bangladeshi citizen; government/NGO employee preferred; bachelor's degree",
    "notes": "",
    "link": "https://koicascholarship.org/koica-bangladesh-scholarship/",
    "benefits": "Full tuition + stipend + airfare + insurance + settling-in allowance",
    "competition": "Medium"
  },
  {
    "name": "CSC Scholarship - Beijing Institute of Technology",
    "university": "Beijing Institute of Technology (BIT)",
    "country": "China",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "Computer Science / Engineering / Sciences",
    "deadline": "March-April 2026",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bachelor's degree; under 35; English or Chinese proficiency",
    "notes": "",
    "link": "https://chinascholarshipcouncil.com/beijing-institute-of-technology-csc-scholarship/",
    "benefits": "Tuition + free accommodation + insurance + CNY 3000/month (Master's)",
    "competition": "Medium"
  },
  {
    "name": "Fulbright Foreign Student Program",
    "university": "U.S. Department of State / IIE",
    "country": "USA",
    "degree": "Master's",
    "priority": "Top",
    "match": 95,
    "field": "All Subjects (incl. Engineering)",
    "deadline": "May-June 2026 (for 2027-28 cohort)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bangladeshi citizen; bachelor's; 3+ yrs work/teaching exp preferred; leadership",
    "notes": "",
    "link": "https://bd.usembassy.gov/call-for-applications-for-the-2026-2027-fulbright-foreign-student-program/",
    "benefits": "Full tuition + living stipend + airfare + health insurance + book allowance",
    "competition": "High"
  },
  {
    "name": "University of Bologna Scholarship",
    "university": "University of Bologna",
    "country": "Italy",
    "degree": "Master's",
    "priority": "Medium",
    "match": 85,
    "field": "All Subjects (incl. Engineering)",
    "deadline": "March (annual)",
    "funding": "Fully Funded",
    "assistantship": "None",
    "eligibility": "Bachelor's degree; SAT/GRE score; English proficiency",
    "notes": "",
    "link": "https://www.unibo.it/en/services-and-opportunities/study-grants-and-subsidies/grants-for-international-students",
    "benefits": "Tuition waiver + €11000/year stipend",
    "competition": "Medium"
  }
];